version: '3'

# Run with `docker-compose up [-d]`.
# View logs with `docker-compose logs [-f]`.
# Use docker-compose.override.yml to further customize your dev environment.

services:
  karen:
    image: snowwm/karen:latest
    env_file: .env
    restart: unless-stopped
